### ISSUE TITLE
TODO list before releasing

### ISSUE THREAD

**Issue by campos20** [thewca/statistics#27]
I'm having less time to dedicate to this project so we are releasing it.

- [x] Assigning a subdomain (impeditive)
- [x] Restrict database query to logged users and point login from staging to prod (Impeditive)
- [x] Hide backend endpoints to create statistics in prod so people won't mess with us (Impeditive)
- [x] Assign a load balancer and use that address instead of server's address so we can be more consistent (we are using elastic IP, which can help, but it's not good enough IMO)
- [x] Start using a dedicated database instead of one that lives in the server
- [x] Use stats from various sources
- [x] Stop using servers and start using ECS
- [x] Change home page and about page
- [x] Add a cron process to calculate stats
- [x] HTTPs
